%% Beta Subband filter

function y = beta_filter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 18-May-2020 17:05:36

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N     = 4;     % Order
    % F3dB1 = 13.5;  % First
    % F3dB2 = 30.5;  % Second
    % Fs    = 128;   % Sampling Frequency
    %
    % h = fdesign.bandpass('n,f3db1,f3db2', N, F3dB1, F3dB2, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.20377061380507 0.626896077248333; 1 0 -1 1 ...
        -0.281948866070443 0.498320059762141], ...
        'ScaleValues', [0.328269839289287; 0.328269839289287; 1]);
end

s = double(x);
y = step(Hd,s);

