%% EEG range filter

function y = range_filt(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 18-May-2020 17:08:12

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N     = 4;    % Order
    % F3dB1 = 0.5;  % First
    % F3dB2 = 50;   % Second
    % Fs    = 128;  % Sampling Frequency
    %
    % h = fdesign.bandpass('n,f3db1,f3db2', N, F3dB1, F3dB2, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.96529083235458 0.965888119511567; 1 0 -1 1 ...
        1.06518061209761 0.381117958891916], ...
        'ScaleValues', [0.775252835818193; 0.775252835818193; 1]);
end

s = double(x);
y = step(Hd,s);

